.test:
  stage: test
  script: bin/acceptance-tests.sh
  tags:
    - mozmeao
    - aws
  after_script:
    - bin/cleanup_after_functional_tests.sh
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: on_failure
    expire_in: 1 week
    paths:
      - "results-${CI_JOB_ID}"
  variables:
    MARK_EXPRESSION: not headless and not download
    TEST_IMAGE: mozmeao/bedrock_test:91e4628067ceab1eae5d2eb9598b79ec95d4bc2d


.saucelabs:
  variables:
    DRIVER: SauceLabs
    PYTEST_PROCESSES: "8"

.remote:
  variables:
    DRIVER: Remote
    PYTEST_PROCESSES: "auto"

.chrome:
  variables:
    BROWSER_NAME: chrome
    MARK_EXPRESSION: "not headless and not download and not skip_if_not_firefox"

.firefox:
  variables:
    BROWSER_NAME: firefox
    MARK_EXPRESSION: "not headless and not download and not skip_if_firefox"

.download:
  variables:
    DRIVER: ""
    MARK_EXPRESSION: download

.headless:
  variables:
    DRIVER: ""
    MARK_EXPRESSION: headless

.ie:
  variables:
    BROWSER_NAME: internet explorer
    MARK_EXPRESSION: "smoke or sanity"
    PLATFORM: Windows 10

.ie9:
  variables:
    BROWSER_NAME: internet explorer
    BROWSER_VERSION: "9.0"
    PLATFORM: Windows 7
    MARK_EXPRESSION: sanity

.edge:
  variables:
    BROWSER_NAME: Microsoft Edge
    PLATFORM: Windows 10
    MARK_EXPRESSION: "not headless and not download and not skip_if_not_firefox"

test-firefox-saucelabs:
  extends:
    - .test
    - .firefox
    - .saucelabs
  when:
    manual

test-ie-saucelabs:
  extends:
    - .test
    - .ie
    - .saucelabs

test-ie9-saucelabs:
  extends:
    - .test
    - .ie9
    - .saucelabs

test-chrome-saucelabs:
  resource_group: giorgos-test-chrome
  extends:
    - .test
    - .chrome
    - .saucelabs
  when:
    manual

test-download-saucelabs:
  extends:
    - .test
    - .download
    - .saucelabs
  when:
    manual

test-edge-saucelabs:
  extends:
    - .test
    - .edge
    - .saucelabs
  when:
    manual

test-firefox-remote:
  extends:
    - .test
    - .firefox
    - .remote

test-headless:
  extends:
    - .test
    - .headless

test-chrome-remote:
  resource_group: giorgos-test-chrome
  extends:
    - .test
    - .chrome
    - .remote

test-download-remote:
  extends:
    - .test
    - .download
    - .remote
  variables:
    BROWSER_NAME: "firefox"
  except:
    changes:
      - "iowa-a/bedrock-dev/*"
    refs:
      - master
      - gitlab-ci-dev
    variables:
      - $CI_PIPELINE_SOURCE == "push"
