apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: bedrock-dev-web-vpa
  namespace: bedrock-dev
spec:
  targetRef:
    apiVersion: "extensions/v1beta1"
    kind:       Deployment
    name:       bedrock-dev-web
  updatePolicy:
    updateMode: "Off"
